name: Docker Activity

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
  workflow_dispatch:
jobs:
  Logintodockerhub:
    runs-on: ubuntu-latest
    environment: raj-env-dev
    steps:
    - uses: actions/checkout@v3
    - name: docker login
      uses: docker/login-action@v2.1.0
      with:
       registry: registry-1.docker.io
       username: ${{secrets.DOCKERHUBUSERNAME}}
       password: ${{secrets.DOCKERHUBPASSWORD}}
    -name: Docker Pull task
     run: docker pull glassfish
    -name: Docker_Tag
     run: docker tag glassfish rajkolli5236/docker_img
    -name: Docker Push  task
     run: docker push rajkolli5236/docker_img:tagname
	
  Logintodockerhub2:
    runs-on: ubuntu-latest
    environment: raj-env-qa
    steps:
    - uses: actions/checkout@v3
    - name: docker login
      uses: docker/login-action@v2.1.0
      with:
       registry: registry-1.docker.io
       username: ${{secrets.DOCKERHUBUSERNAME}}
       password: ${{secrets.DOCKERHUBPASSWORD}}